version: '3.3'

services:
  # An Apodini Buoy Web Service
  buoy-web-service:
    container_name: "buoy-web-service"
    image: "ghcr.io/fa21-collaborative-drone-interactions/buoywebservice:latest"
    # Expose port 80 of container on port 80 of host
    ports:
      - "80:80"
    # Mount directory for config and sensor data
    volumes:
      - ../buoy:/buoy
    # Pass the desired port and the path to the mounted database volume to the Apodini web service
    command: ["--port", "80"]
