version: '3.3'

services:
  # An Apodini Buoy Web Service
  buoy-web-service:
    container_name: "buoy-web-service"
    image: "ghcr.io/fa21-collaborative-drone-interactions/buoywebservice:latest"
    build:
      context: ./
      dockerfile: ./WebService/Dockerfile
    ports:
      - "80:80"
    # Pass the desired port and the path to the mounted database volume to the Apodini web service
    command: ["--port", "80"]
