version: '3.3'

services:
  # An Apodini Buoy Web Service
  buoy-web-service:
    container_name: "buoy-web-service"
    image: "ghcr.io/fa21-collaborative-drone-interactions/buoywebservice:latest"
    build:
      context: ./
      dockerfile: ./WebService/Dockerfile
    # Expose port 8080 of container on port 443 of host
    ports:
      - "80:80"
    # Mount directory for config and sensor data
    volumes:
      - ../buoy:/buoy
