name: Evaluation

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  evaluate_buoy:
    runs-on: self-hosted
    steps:
    - name: Clone Deployment Provider Repo
      uses: actions/checkout@v2
      with:
        repository: 'hendesi/buoy-deployment-provider'
        ref: develop
    - name: Clone WebService Repo
      uses: actions/checkout@v2
      with:
        path: buoy-deployment-provider
    - name: Create Config File
      run: > 
          echo "
                [
                  {
                    "\"_workstation._tcp.\"":
                    {
                        "\"username"\": "\"ubuntu"\",
                        "\"password"\": "\"raspberry"\"
                    }
                  },
                  {
                    "\"docker-compose"\": 
                    {
                      "\"username"\": "\"$docker_username"\",
                      "\"password"\": "\"$docker_password"\"
                    }
                  }
                ]
                " > config.json
      env:
          docker_username: ${{ secrets.DOCKER_UN_SECRET }}
          docker_password: ${{ secrets.DOCKER_SECRET }}
    #- name: Build Provider
    # run:  swift build
    - name: Test
      run:  echo "${ls -a}"
    # - name: Run Provider
    #  run:  bash scripts/buoy_simulation
